### ISSUE TITLE
Social media icons widgets for sidebar and footer widget area

### ISSUE THREAD

**Issue by puikinsh** [ColorlibHQ/shapely#173]
Social media icons widgets that could be used in the sidebar as well as footer would be great.

**Comment by cristianraiber** [comment]
@puikinsh - This will be provided by Kiwi shortly. Do you still want a custom widget bundled inside the companion of Shapely that provides the same functionality?

**Comment by puikinsh** [comment]
I am fine with Kiwi as long as it blends in with the theme design. Custom styling is a must.

**Comment by cristianraiber** [comment]
@giucu91 - we need to make sure Kiwi blends in nicely with Shapely, design wise.

**Comment by giucu91** [comment]
@cristianraiber , @c0sm1n87 I'm not sure I understand what is needed here. Do we need social buttons ( which will redirect to a facebook profile, twitter profile, etc) or share buttons ?

**Comment by cristianraiber** [comment]
@giucu91 - we need to implement Kiwi & also add inside Kiwi a widget that can display social sharing buttons / icons.

**Comment by cristianraiber** [comment]
@ngabyn - we still need help here with the integration of Kiwi into Shapely - design wise.

**Comment by giucu91** [comment]
@cristian-e we should use the **Navigation Menu** widget from WP Core and style the menu items based on the url of this link here : https://github.com/ColorlibHQ/tyche/blob/master/assets/css/style.css#L2745

**Comment by giucu91** [comment]
We already have something : https://github.com/ColorlibHQ/shapely/blob/master/style.css#L3398
