### ISSUE TITLE
Multiple small bugs

### ISSUE THREAD

**Issue by a-support** [ColorlibHQ/shapely#268]
Hello,

A user was able to find a few issues in the theme outlined here:

https://colorlib.com/wp/forums/topic/bug-a-few-random-php-bugs-typos/

Cheers

**Comment by biziclop** [comment]
Hi, here's another small one, but I don't know if its also that's easy to fix as the others:

`themes/shapely/inc/custom-controls/class-shapely-logo-dimensions.php`:
throws
`PHP Notice:  Array to string conversion in …/wordpress/wp-includes/formatting.php on line 1049`
because Shapely_Logo_Dimensions->value() is an array, but it's parent class WP_Customize_Control->render_content() expects ->value() to be a html-attribute-compatible value.

    #0 …/wordpress/wp-includes/formatting.php(3981): wp_check_invalid_utf8(Array)

    #1 …/wordpress/wp-includes/class-wp-customize-control.php(653): esc_attr(Array)
            <input
              <?php if ( ! isset( $this->input_attrs['value'] ) ) : ?>
                value="<?php echo esc_attr( $this->value() ); ?>"
              <?php endif; ?>

    #2 …/wordpress/wp-includes/class-wp-customize-control.php(425): WP_Customize_Control->render_content()
    #3 …/wordpress/wp-includes/class-wp-customize-control.php(412): WP_Customize_Control->render()
    #4 …/wordpress/wp-includes/class-wp-customize-control.php(377): WP_Customize_Control->maybe_render()
    #5 …/wordpress/wp-includes/class-wp-customize-control.php(315): WP_Customize_Control->get_content()
    #6 …/wordpress/wp-includes/class-wp-customize-control.php(333): WP_Customize_Control->to_json()

    #7 …/content/themes/shapely/inc/custom-controls/class-shapely-logo-dimensions.php(40): WP_Customize_Control->json()
    class Shapely_Logo_Dimensions extends WP_Customize_Control {
      public function get_dimensions() {
        $current_value = $this->value();
        if ( ! $current_value ) {
          $current_value = array(
            'width'  => '',
            'height' => '',
            'ratio'  => 1,
          );
        return $current_value;
      }

    #8 …/wordpress/wp-includes/class-wp-customize-manager.php(4770): Shapely_Logo_Dimensions->json()
    #9 [internal function]: WP_Customize_Manager->customize_pane_settings(\'\')
    #10 …/wordpress/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
    #11 …/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(\'\', Array)
    #12 …/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
    #13 …/wordpress/wp-admin/customize.php(258): do_action(\'customize_contr...\')
    #14 {main}

**Comment by cristian-e** [comment]
@biziclop . 
Can you please show us the steps to reproduce this error. 

It will definitely help in order to identify the bug and fix this issue.
Thank you.

**Comment by biziclop** [comment]
Dear @cristian-e, I tried to reproduce the bug myself with a clean install, just WordPress (latest v4.9.8), and the Shapely theme (installed from WordPress admin, v1.2.3), and nothing else (no demo content, no suggested plugins. etc.).

The most important step seems to be having `define('WP_DEBUG', true );` in `config.php`,
then going to `Appearance/Customize/Theme Options/Site Identity`, then selecting and uploading a logo, publishing. Still no errors.

But reload `/wp-admin/customize.php`, and you will see `PHP Notice: Array to string conversion in /…/wp-includes/formatting.php on line 1045`

Actually the error appears even after removing the site logo, then reloading `customize.php`.
