### ISSUE TITLE
Number of portfolio elements

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/shapely#269]
this is a feature request to add a feature to control the number of portfolios on the homepage

**Comment by cristianraiber** [comment]
@nodarik - you mean the number of elements inside the portfolio ?

**Comment by cristianraiber** [comment]
@nodarik - please answer my above question. 

cc @puikinsh

**Comment by marisolps** [comment]
What he means is the number of projects displayed at the parallax homepage. For some reason, even when editing the code (google it) the widget does not show more than 10. However, if you click on portfolio you will be able to see more if you change the settings accordingly. This bug has been around for some time with solutions posted for previous versions, but with the latest update it seems impossible to fix. Thanks for your help.

**Comment by marisolps** [comment]
[https://colorlib.com/wp/forums/topic/show-more-than-10-portfolio-items/]

**Comment by cristianraiber** [comment]
@marisolps - thanks for the explanation :) this actually helps a lot!

Cristian.

**Comment by cristianraiber** [comment]
![ezgif-2-232a52692f](https://user-images.githubusercontent.com/7841556/46204841-4c892f80-c327-11e8-8778-1905ba3551f1.gif)

**Comment by cristianraiber** [comment]
@marisolps @nodarik  - You can see from my GIF above that changing number of projects works. Is there something I'm missing here? Why did you go in and change the code ? :)

**Comment by marisolps** [comment]
Hi, your gif still shows only 10 projects.
As explained, you can change it in the backend but it does not show more
than 10 in the parallax homepage. This has been reported for years and the
solution was editing the code, with the latest update that no longer works.

Please send me an example showing more than 10 projects in the homepage and
let me know how you did it.

**Comment by cristianraiber** [comment]
@marisolps - if you look closer, my GIF shows the change from 10 to 11 projects. Meaning, there's no 10 limit for projects.

**Comment by marisolps** [comment]
But they do not show in the homepage! You can put whatever number but they
don’t show!

**Comment by cristianraiber** [comment]
@marisolps - We tested this as well and it's working fine at our end. Could you please tell me the exact list of plugins you're using? Maybe something is messing with Shapely.

P.S: We're running Shapely 1.2.3 & Shapely Companion 1.2.3

**Comment by cristian-e** [comment]
I'm using the latest version of shapely as well, and I can't replicate this issue.
![ezgif com-resize](https://user-images.githubusercontent.com/43263346/46212802-8e25d480-c33f-11e8-9eea-76f756501579.gif)

**Comment by marisolps** [comment]
Cristian,

YOU ARE AMAZING!!! Not even the people from Colorlib was able to show me
where to change the settings. They were saying that it was here:
[image: Capture_WP_Portfolio.PNG]

No one mentioned to change it in the widget section as well. As you can see
there is two places where you need to change the project number.

I have searched everywhere and I invite you to check on google too,
everyone went for the code!

See my question and their answer here:
Post Link: https://colorlib.com/wp/forums/topic/cant-change-the-number-of-
portfolio-items/#post-184993
<https://u2876342.ct.sendgrid.net/wf/click?upn=DDNt3l-2FJtxvRQ73Rjp9GaTEMhuPPrIACYprNo0I9yLBNMMATFE-2BWzhgQTrok5bUUp43tGARL-2Bc-2FXiN6f7fKzwl6oNUghVLmLJHCHzwAgOL4lefVzWU4IoEaT5UTxORuTQyr-2ByKi1DDay8fheL6RJwg-3D-3D_vAoLR1r9Q2tul2kEDRwYDuBdv5SpEAUYfrXeT1hZBkmZ0RAdvrDRXd73UTPDerPSKiKzVEA-2B8fwoRw-2FjK4lQKBsUCv-2FBz5aHekM6KlXKspkCusqTgMdbW24JUmxp6oYzZ3v6ROyezy6pFPL-2B6c-2BRozLKRkkhuTZydMegKQKsfWnfJiZtgmUti6NoCdt6-2FtISGGiV9XqMiexGFT-2Be34utDO9ETEwr8Fb79F4yNTiWoOi0NHKmS3uySE69E0wVFX39vI0CWbCPFVw56oZ20vhxag-3D-3D>


THANKS SO MUCH!!!! YOU ARE THE BEST!

Mary

**Comment by cristianraiber** [comment]
@marisolps - glad it's all fixed then :)
