### ISSUE TITLE
Widgets Reset on Page Title Change

### ISSUE THREAD

**Issue by trdef** [ColorlibHQ/shapely#275]
Hi,

I've found recently that updating a page title will remove all widget settings from the page, essentially resetting the template.

Is there any way around this (currently, we have pages set as www.domain.com/page1 and will need to change them to www.domain.com/notpage1)?

**Comment by Vickyb59** [comment]
Can this be removed from issues as it clearly has been fixed?

**Comment by mahendrapratap4022** [comment]
yes, It is fixed.
