### ISSUE TITLE
Placing a Parallax Section between specific widgets causes a wrong image frame

### ISSUE THREAD

**Issue by Offek** [ColorlibHQ/shapely#285]
Hello,
First of all, thanks for a great theme.
When I attempt to place a parallax section between a Client Section and a Contact Form, and set the the image position to background, the parallax image is completely misplaced and goes over the contact form. Please take a look at the following screenshots.

When the Section is above the Client Section:
<img width="1075" alt="screen shot 2019-02-28 at 12 39 33 am" src="https://user-images.githubusercontent.com/1673069/53528190-7f5f6b80-3af1-11e9-9cb9-8eb638578685.png">

When the Section is between the Client Section and the Contact Form:
<img width="1033" alt="screen shot 2019-02-28 at 12 25 09 am" src="https://user-images.githubusercontent.com/1673069/53528195-82f2f280-3af1-11e9-9f79-d549bc486fcb.png">

Sometimes it shows fine, but after a simple refresh the issue occurs again.
I doubt it is a problem with my environment, as I disabled all the widgets and the issue still occurs.
I'm running the latest version of the theme and WordPress.

Thanks in advance!

**Comment by razvanaldea89** [comment]
Managed to remake the bug but only for a brief moment, after that it went back to normal. Taking a closer look.

**Comment by Vickyb59** [comment]
Looks like this issue has been fixed as I haven't been able to recreate the said bug.

![Screenshot (26)](https://user-images.githubusercontent.com/48920873/126669894-b8149f7a-37a2-4681-95bf-e2253991db89.png)
![Screenshot (27)](https://user-images.githubusercontent.com/48920873/126669900-93c34924-5f17-46a9-8127-bb5443e09a0a.png)

**Comment by Vickyb59** [comment]
Administrator should work on removing fixed issues from issues section.

**Comment by mahendrapratap4022** [comment]
Hi all, its fixed in https://github.com/ColorlibHQ/shapely/pull/319
