### ISSUE TITLE
Parallax section for front page – no effect on mobiles :-(

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/shapely#286]
Even on our demo parallax effect doesn’t work on mobile devices. Not on an iPhone with current iOS nor on an android phone

Reported here: 
https://colorlib.com/wp/forums/topic/parallax-section-for-front-page-no-effect-on-mobiles/

**Comment by cristianraiber** [comment]
That's a limitation in the JS script used for parallax effects. Unfortunately, parallax on iOS is a lot of trouble.
