### ISSUE TITLE
Autoplay toggle not working for Shapely video widget

### ISSUE THREAD

**Issue by asebold** [ColorlibHQ/shapely#287]
Hi, I'm using Shapely here https://wicounts.com/ (password: Engage2020!). For the video, regardless of whether I have autoplay on or off in the customizer, the video always autoplays. 

Here is the code that renders on the page. You can see `data-autoplay=0` for the container, however on the iframe for the video it says `allow=autoplay;` and on the src attribute for the iframe the youtube url contains `autoplay=1` as a parameter. 

````					
<div data-video-id="COAVR0CMTIw" data-autoplay="0" data-mute="0" class="video-widget youtube loaded">
	<span class="video-controls">
		<button class="play-button"><icon class="fa fa-play"></icon></button>
		<button class="pause-button"><icon class="fa fa-pause"></icon></button>
	</span>
		<div id="ytplayer-container1555006181218" class="ytplayer-container background">                                    
			<iframe id="YTPlayer-ID-1555006181218" class="ytplayer-player" style="width: 1552px; height: 873px; left: 0px; top: -207.5px;" frameborder="0" allowfullscreen="1" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" title="YouTube video player" width="1552" height="873" src="https://www.youtube.com/embed/COAVR0CMTIw?iv_load_policy=3&amp;modestbranding=1&amp;autoplay=1&amp;controls=0&amp;showinfo=0&amp;wmode=opaque&amp;branding=0&amp;autohide=0&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fwicounts.com&amp;widgetid=1"></iframe>                                    
		</div>                                    
	<div id="ytplayer-shield" class="ytplayer-shield">
	</div>
</div>
````

Please advise.

**Comment by cristianraiber** [comment]
If you're using iOS autoplay will never work. It's a known limitation.

**Comment by asebold** [comment]
This is on desktop, Chrome and Firefox.

**Comment by MalouNetlight** [comment]
Hello, I am also facing this issue using shapely and the video widget. I would like to disable the autoplay function but the toggle doesn't work. 

Any fixes planned?

**Comment by mahendrapratap4022** [comment]
fixed in https://github.com/ColorlibHQ/shapely/pull/320
