### ISSUE TITLE
FontAwesome icons not showing up

### ISSUE THREAD

**Issue by bvegso** [ColorlibHQ/shapely#288]
It looks like WordPress 5.1.1 (and Beaver Builder 2.2.2.5?) transitioned to Font Awesome 5 Free, but Shapely is still referencing the Font Awesome 4 conventions:

```
#social li a[href*="instagram.com"] .fa:before,
.fa-instagram:before {
	content: "\f16d"
}

<a target="_blank" href="https://www.instagram.com/xyz/">
  <i class="social_icon fa">
    <span>Instagram</span>
  </i>
</a>
```

According to this guide, it should be using the class name "fab", instead of "fa". This would also instruct some mechanism (maybe Beaver Builder?) on my site to load fa-brands-400.woff2:
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Beaver Builder troubleshooting: https://kb.wpbeaverbuilder.com/article/645-troubleshooting-font-awesome-icons

If I just add custom CSS and use the inspector to change the class to "fab", it starts working:
```
#social li a[href*="facebook.com"] .fab:before,
.fa-facebook-f:before,
.fa-facebook:before {
	content: "\f09a"
}

<a target="_blank" href="https://www.instagram.com/xyz/">
  <i class="social_icon fab">
    <span>Instagram</span>
  </i>
</a>
```

Or if I could use the Menu editor to add a custom class to the menu item - but I understand the clever CSS rule for automagically do this.

**Comment by Vickyb59** [comment]
This has been fixed. Font awesome version has been updated. This issue should be closed

**Comment by bvegso** [comment]
Thanks @Vickyb59, do you know when this will be released?

**Comment by Vickyb59** [comment]
@bvegso, unfortunately, I have no idea about that. The project manager/Admin should be in the best position to answer.

**Comment by mahendrapratap4022** [comment]
@bvegso font-awesome is updated to 5 in version 1.2.13 with the PR https://github.com/ColorlibHQ/shapely/pull/315 which is created by @Vickyb59
