### ISSUE TITLE
Import demo bug

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/shapely#291]
If I manually activate the plugins
![import bug](https://user-images.githubusercontent.com/44024114/62678193-6f5d8900-b9b9-11e9-89d5-a3849cb6d426.PNG)
When trying to import the demo it does nothing and remains in the same state
![import bug 2](https://user-images.githubusercontent.com/44024114/62678223-88fed080-b9b9-11e9-8277-5c61925fc137.PNG)

**Comment by razvanaldea89** [comment]
Note that if I refresh the page the import works.

**Comment by mahendrapratap4022** [comment]
@razvanaldea89 I have checked it many times and found nothing I have tried the same way as you said with plugins and demo content maybe it is fixed in the new version. if not then you can share the exact scenario with me.
