### ISSUE TITLE
Multiple different OUTDATED Versions donwloadable on the web / is it still Open source ?

### ISSUE THREAD

**Issue by hubyhuby** [ColorlibHQ/shapely#294]
The versions downloadable of Shapely on the web are not current. As of 09/08/2019 : 
* https://github.com/ColorlibHQ/shapely/releases  gives you  : v1.2.3: Merge pull request #266 from MachoThemes/master

* https://colorlib.com/out/download-shapely/ Gives you "1.1.2"
* And update from WP says 1.2.5

**Comment by hubyhuby** [comment]
2 Mai 2021
So, today we have 3 different version on the web... it seams : 

From my WP instance :
![image](https://user-images.githubusercontent.com/26340942/116807273-8bf90780-ab32-11eb-8c41-7c09e14de791.png)
from WP .org
![image](https://user-images.githubusercontent.com/26340942/116807286-a16e3180-ab32-11eb-8548-a25ff9cd9869.png)

DIFFERENT from your website : 
![image](https://user-images.githubusercontent.com/26340942/116807298-b5199800-ab32-11eb-9eff-c5bd4b4f71ed.png)

DIFFERENT from this github repos : 
![image](https://user-images.githubusercontent.com/26340942/116807317-d4b0c080-ab32-11eb-9893-6f1a041163cb.png)

**Comment by hubyhuby** [comment]
Wondering if this template is still open source ? No revision on github since January 2020 ? And we have a MArch 20201 update on colorlib website

**Comment by mahendrapratap4022** [comment]
Hi @hubyhuby the current version is 1.2.13 and yes it is still open source we are now trying our best to giving it full support and update. And it will take some time to update newer version on colorlib website till then you can download it from here.
