### ISSUE TITLE
Kali form problem

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/shapely#296]
in the last update 2.0.5 when Kali for is added option to choose contact form 7 is not functioning

Steps to replicate:
in the customizer, try to choose form from contact form 7, it only shows radio button but no option to choose any form

**Comment by ThiBenn** [comment]
Any news on that issue ?

**Comment by mahendrapratap4022** [comment]
Hi @nodarik @ThiBenn anyone can you please share the screenshot from the customizer or where you are getting the issue I'm not getting I just tested and it working fine.
