### ISSUE TITLE
Submenu problem in IE11

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/shapely#298]
Submenus are not working in IE11, this happens even on our demo, please check 1st and 2nd level menus

the problem is pseudo  :focus-withing selector that brakes rule

**Comment by a-support** [comment]
The issue is also happening on the Edge Browser. The sub-menus do not seems but work just fine on other browsers.

**Comment by skuhnow** [comment]
I have the same problem

**Comment by skuhnow** [comment]
Found a solution [here](https://colorlib.com/wp/forums/topic/drop-down-menus-in-shapely-not-working-wit-ie-and-edge/)

**Comment by mahendrapratap4022** [comment]
Please add this CSS in appearance - customize - additional CSS

.main-navigation .menu > li:hover > ul {
opacity: 1;
transform: translate3d(0, 0px, 0);
-webkit-transform: translate3d(0, 0px, 0);
-moz-transform: translate3d(0, 0px, 0);
visibility: visible;
}
.main-navigation .menu>li>ul li:hover>a {
opacity: 1;
}

Thanks!
