### ISSUE TITLE
Update Font Awesome to 5.12.0

### ISSUE THREAD

**Issue by martijn19811** [ColorlibHQ/shapely#300]
The current Font Awesome set implemented in the Shapely theme is still set on 4.5.2, but the current theme is already 5.12.0. This update will provide the user with much more usable icons. Plus performance will also improve, as this latest font set is much lighter than the 4.X version,

**Comment by MatthiasLohr** [comment]
@cristianraiber, is the shapely project discontinued?

**Comment by cristianraiber** [comment]
@MatthiasLohr - no, it is not discountinued. An update will be available soon to add this.

**Comment by mahendrapratap4022** [comment]
Font Awesome is updated in https://github.com/ColorlibHQ/shapely/pull/315
