### ISSUE TITLE
Shapely Content widget is not working

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/shapely#301]
Shapely Content widget is not working, data from the page content is not displayed on the frontend by using the content widget

**Comment by mahendrapratap4022** [comment]
@nodarik can you provide some more details as I can check the widget is working fine on the page. It would be great if you can provide a screenshot of it if you are still facing it.

**Comment by mahendrapratap4022** [comment]
Closing the request if you face any issue again similar to this please reopen the issue or create new one with proper details.
