### ISSUE TITLE
Recommended actions annoyingly visible in Customizer

### ISSUE THREAD

**Issue by Harm10** [ColorlibHQ/shapely#302]
I can understand your wish to display the recommended actions but even when I click them as viewed (the eye icon) they are still displayed in Customizer sidebar (and even more annoying at the top of all choices).
Can this be changed?

**Comment by mahendrapratap4022** [comment]
Hi @Harm10 I have just checked when we click on the view button it is never showing again. It might fixed in https://github.com/ColorlibHQ/shapely/pull/313
Thanks
