### ISSUE TITLE
Welcome to Shapely can only be removed by clicking X

### ISSUE THREAD

**Issue by Harm10** [ColorlibHQ/shapely#303]
The Welcome to Shapely information remains displayed on the Dashboard even after I clicked the Setup Shapely button. I have to click the X to get rid of it. I think clicking the button should also make it disappear?

**Comment by mahendrapratap4022** [comment]
Hi @Harm10 it is fixed in https://github.com/ColorlibHQ/shapely/pull/313
Thanks and let me know if you face any issue further.

**Comment by DesktopMasters** [comment]
I am facing this issue now.
I have a user with "editor" level access.  They do not even have access to setup shapely.  They get that dialog on every refresh even after hitting the "X".  As well, the theme is already setup.
