### ISSUE TITLE
jQuery Migrate:

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/shapely#305]
many functions of the theme are broken after the latest update WordPress 5.6.

Jquery version must be updated

**Comment by razvanaldea89** [comment]
Hello @nodarik , we are looking into it and an update is going to be released soon with these fixes. Thank you for your patience.

**Comment by razvanaldea89** [comment]
Hello again @nodarik , just tested out some of the theme's functions but seem OK. Could you please give us more info and perhaps a link to the website that has those problems?

**Comment by mahendrapratap4022** [comment]
Hi @nodarik I have added PHP 8 and WP 5.7 support in https://github.com/ColorlibHQ/shapely/pull/313 
let me know here if are facing any issue now.
Thanks
