### ISSUE TITLE
Changelog out of sync

### ISSUE THREAD

**Issue by MalouNetlight** [ColorlibHQ/shapely#306]
Hello, I really like the shapely theme and saw that you just released version 1.2.10. I wanted to know what you changed/fixed/added in the new version but can find only the changelogs until version 1.2.4:

https://github.com/ColorlibHQ/shapely/blob/7b6c0ec970f1ddfff9343653c9718bbdece5f4fb/changelog.txt#L1

Do you plan to update the changelog? Thanks in advance. 

A happy user

**Comment by mahendrapratap4022** [comment]
Hi, @MalouNetlight thanks for letting us know, from now on we are actively maintaining all ColorlibHQ repositories. You can check we have updated the shapely changelog and also added PHP 8 support.

Thanks
Happy to help.
