### ISSUE TITLE
Deprecated message php 7.4

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/shapely#325]
Deprecated : Unparenthesized a ? b : c ? d : e is deprecated. Use either (a ? b : c) ? d : e or a ? b : (c ? d : e) in /home/wildincu/public_html/wp-content/themes/shapely/inc/extras.php on line 442

Reported here:
https://colorlibsupport.com/t/hello-help-with-shapely-error-please/29971

**Comment by mahendrapratap4022** [comment]
Hi it is already solved in https://github.com/ColorlibHQ/shapely/pull/323
I also test with the 7.3 and 7.4 versions of PHP.
