### ISSUE TITLE
Angle down \f107 (Font Awesome 5) is not working

### ISSUE THREAD

**Issue by lpla** [ColorlibHQ/shapely#327]
Hi. Seems like some changes are needed in `style.css` in order to Font Awesome 5 could work properly. For example, for `\f107` (and guess that similar ones, but I don't use them in my sites). Check this SO issue: https://stackoverflow.com/questions/47788847/font-awesome-5-font-family-issue

Otherwise, they will show like this: 

![Screenshot from 2021-09-01 15-24-55](https://user-images.githubusercontent.com/1533393/131679306-53060da2-8773-49bc-801b-49e7be833c0c.png)

I fixed it in my site by editing `style.css` replacing `font-family: 'fontawesome'` with `font-family: 'Font Awesome\ 5 Free'`. Also replacing `font-weight: normal` with `font-weight: 900`.

I didn't do a pull request because I am not really sure this is the correct fix for this issue, or if this is needed in more places other than `.dropdown:after`.

**Comment by mahendrapratap4022** [comment]
@lpla you are right about the same, here is the PR for the same the issue has been fixed. https://github.com/ColorlibHQ/shapely/pull/328
